version: "3.10"

x-postgres-environment: &x-postgres-environment
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_NAME: ${POSTGRES_NAME}

services:
  database:
    image: postgres:latest
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      <<: *x-postgres-environment

  backend:
    build: backend
    restart: always
    volumes:
      - "./backend/app/:/application"
    environment:
      <<: *x-postgres-environment
      SECURITY_KEY: ${SECURITY_KEY}
    ports:
      - '8000:8000'

volumes:
  pgdata:
